### PR TITLE
427 fix proof building issue from archives on mainnet

### LINKED ISSUE #427: Fix proof-building issue from archives on mainnet
We are currently facing some issues with proof-building on our Amplitude spacewak clients. 
The problem is that when fetching envelopes from the transaction archive, the archived entries contain 14 envelopes. 
Our calculation of [get_min_externalized_messages](https://github.com/pendulum-chain/spacewalk/blob/8bb0d639c6f2e23126f72e39f56c6a497cf2e2d4/clients/vault/src/oracle/types/constants.rs#L27) makes us require at least 15 envelopes for building a proof though, called [here](https://github.com/pendulum-chain/spacewalk/blob/8bb0d639c6f2e23126f72e39f56c6a497cf2e2d4/clients/vault/src/oracle/collector/proof_builder.rs#L135).
We should probably loosen this requirement a bit but not too much. I'm not yet sure what the exact science for this would be. Maybe we don't calculate it but use fixed values for mainnet and testnet respectively.

### PR DESCRIPTION
**Pull request by b-yap**
closes #427

### CODE REVIEW

File: clients/vault/src/oracle/types/constants.rs [hunk 1]
```diff
@@ -29,5 +29,5 @@ pub fn get_min_externalized_messages(public_network: bool) -> usize {
 		if public_network { VALIDATOR_COUNT_PUBLIC_NETWORK } else { VALIDATOR_COUNT_TEST_NETWORK };
 	// Return 2/3 of the validator count as minimum amount
 	// This value is likely higher than the actual minimum but it's a good approximation
-	validator_count * 2 / 3
+	validator_count * 2 / 3 - 1
```
Comment (ebma) [inline clients/vault/src/oracle/types/constants.rs:32]: No need for this with the archive flag implementation. Let's keep it at count*2/3

**Review by ebma — APPROVED** [review]
Looks good overall, do you still want to add something or why is it a draft @b-yap?

File: clients/vault/src/oracle/types/constants.rs (hunk 1 above)
Comment (b-yap) [reply clients/vault/src/oracle/types/constants.rs]: removed `-1`

File: clients/stellar-relay-lib/src/config.rs [hunk 2]
```diff
@@ -39,6 +39,10 @@ impl StellarOverlayConfig {
 		let cfg = &self.connection_info;
 		let secret_key = SecretKey::from_encoding(secret_key)?;
 
+		let public_key = secret_key.get_public().to_encoding();
+		let public_key = std::str::from_utf8(&public_key).unwrap();
+		log::info!("CONNECTED TO KEY: {public_key}");
```
Comment (ebma) [inline clients/stellar-relay-lib/src/config.rs:44]: Let's give more context in this comment. Something like, 
"Connected to Stellar overlay network with public key:  {public_key}"

File: clients/stellar-relay-lib/src/connection/connector/connector.rs [hunk 3]
```diff
@@ -76,12 +76,18 @@ impl Connector {
 			remote_info.sequence(),
 			auth_msg.sequence
 		);
+
+		let auth_msg_xdr = auth_msg.to_base64_xdr();
+		let auth_msg_xdr = std::str::from_utf8(&auth_msg_xdr).unwrap();
+		log::info!("the auth message: {auth_msg_xdr}");
```
Comment (ebma) [inline clients/stellar-relay-lib/src/connection/connector/connector.rs:82]: Also here, let's rewrite with more text

File: clients/stellar-relay-lib/src/connection/overlay_connection.rs [hunk 4]
```diff
@@ -86,8 +86,8 @@ impl StellarOverlayConnection {
 		local_node: NodeInfo,
 		conn_info: ConnectionInfo,
 	) -> Result<StellarOverlayConnection, Error> {
-		log::info!("Connecting to: {}:{}", conn_info.address, conn_info.port);
-		log::trace!("Connecting to: {conn_info:?}");
+		//log::info!("Connecting to: {}:{}", conn_info.address, conn_info.port);
```
Comment (ebma) [inline clients/stellar-relay-lib/src/connection/overlay_connection.rs:89]: Nit: remove stale comment

File: clients/vault/src/oracle/collector/proof_builder.rs [hunk 5]
```diff
@@ -128,8 +128,11 @@ impl ScpMessageCollector {
 		sender: &StellarMessageSender,
 	) -> Option<UnlimitedVarArray<ScpEnvelope>> {
 		if let Some(envelopes) = self.envelopes_map().get(&slot) {
-			// lacking envelopes
-			if envelopes.len() < get_min_externalized_messages(self.is_public()) {
+			// Lacking envelopes.
+			// If the data was provided from the archive, no need to check for the minimum
```
Comment (ebma) [inline clients/vault/src/oracle/collector/proof_builder.rs:132]:
```suggestion
			// If the data was provided from the archive, no need to check for the minimum
			// Otherwise, we are still lacking envelopes.
```

File: clients/vault/src/oracle/collector/proof_builder.rs [hunk 6]
```diff
@@ -279,6 +283,7 @@ impl ScpMessageCollector {
 						}
 
 						let mut envelopes_map = envelopes_map_arc.write();
+						let mut from_arc_map = env_from_archive_map.write();
```
Comment (ebma) [inline clients/vault/src/oracle/collector/proof_builder.rs:286]: Let's rename to `from_archive_map`. Otherwise one might confuse it with the `Arc<>` type of Rust

Comment (b-yap) [reply clients/vault/src/oracle/collector/proof_builder.rs]: done

File: clients/vault/src/oracle/collector/proof_builder.rs (hunk 5 above)
Comment (b-yap) [reply clients/vault/src/oracle/collector/proof_builder.rs]: done

File: clients/stellar-relay-lib/src/connection/connector/connector.rs (hunk 3 above)
Comment (b-yap) [reply clients/stellar-relay-lib/src/connection/connector/connector.rs]: done

**Review by ebma — APPROVED** [review]
LGTM, good job @b-yap 👍
